create table Area (active bit not null, id integer not null, messageSorting tinyint, originAngle integer, originLatitude float(23), originLongitude float(23), parent_id integer, siblingSortOrder FLOAT default 0.0, treeSortOrder INT default 0, type tinyint, version integer, created datetime(6), updated datetime(6), lineage varchar(256), legacyId varchar(255), mrn varchar(255), geometry GEOMETRY, primary key (id)) engine=InnoDB;
create table Area_editorFields (Area_id integer not null, editorFields varchar(255)) engine=InnoDB;
create table AreaDesc (entity_id integer, id integer not null, lang varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table AtonNode (changeset integer not null, id integer not null, lat float(53) not null, lon float(53) not null, uid integer not null, version integer not null, visible bit not null, timestamp datetime(6), user varchar(255), geometry GEOMETRY not null, primary key (id)) engine=InnoDB;
create table AtonTag (atonNode_id integer, id integer not null, k varchar(255), v varchar(255), primary key (id)) engine=InnoDB;
create table Attachment (id integer not null, indexNo integer not null, message_id integer, fileSize bigint not null, fileName varchar(255), height varchar(255), path varchar(255), type varchar(255), width varchar(255), display enum ('ABOVE','BELOW','SEPARATE_PAGE'), primary key (id)) engine=InnoDB;
create table AttachmentDesc (entity_id integer, id integer not null, caption varchar(1000), lang varchar(255), primary key (id)) engine=InnoDB;
create table BaseMessagePromulgation (id integer not null, message_id integer, promulgate bit not null, type_id integer, version integer, created datetime(6), updated datetime(6), primary key (id)) engine=InnoDB;
create table BatchData (domain_id integer, id integer not null, progress integer, user_id integer, created datetime(6), instanceId bigint, jobNo bigint, dataFileName varchar(255), jobName varchar(255), properties TEXT, primary key (id)) engine=InnoDB;
create table Category (active bit not null, id integer not null, parent_id integer, siblingSortOrder FLOAT default 0.0, treeSortOrder INT default 0, version integer, created datetime(6), updated datetime(6), lineage varchar(256), atonFilter varchar(255), legacyId varchar(255), messageId varchar(255), mrn varchar(255), type enum ('CATEGORY','TEMPLATE'), primary key (id)) engine=InnoDB;
create table Category_Domain (Category_id integer not null, domains_id integer not null) engine=InnoDB;
create table Category_editorFields (Category_id integer not null, editorFields varchar(255)) engine=InnoDB;
create table Category_scriptResourcePaths (Category_id integer not null, indexNo integer not null, scriptResourcePaths varchar(255), primary key (Category_id, indexNo)) engine=InnoDB;
create table Category_stdTemplateFields (Category_id integer not null, stdTemplateFields varchar(255)) engine=InnoDB;
create table Category_TemplateParam (Category_id integer not null, indexNo integer not null, templateParams_id integer not null, primary key (Category_id, indexNo)) engine=InnoDB;
create table CategoryDesc (entity_id integer, id integer not null, lang varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table Chart (active bit not null, id integer not null, internationalNumber integer, scale integer, version integer, created datetime(6), updated datetime(6), chartNumber varchar(255) not null, horizontalDatum varchar(255), legacyId varchar(255), name varchar(255), geometry GEOMETRY, primary key (id)) engine=InnoDB;
create table Comment (acknowledgedBy_id integer, id integer not null, message_id integer, user_id integer, acknowledgeDate datetime(6), created datetime(6), comment longtext, primary key (id)) engine=InnoDB;
create table Comment_emailAddresses (Comment_id integer not null, emailAddresses varchar(255)) engine=InnoDB;
create table Contact (id integer not null, version integer, created datetime(6), updated datetime(6), email varchar(255) not null, language varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table DateInterval (allDay bit, id integer not null, indexNo integer not null, messagePart_id integer, fromDate datetime(6), toDate datetime(6), primary key (id)) engine=InnoDB;
create table Dictionary (id integer not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table DictionaryEntry (dictionary_id integer, id integer not null, atonFilter varchar(255), dict_key varchar(255) not null, primary key (id)) engine=InnoDB;
create table DictionaryEntryDesc (entity_id integer, id integer not null, longValue varchar(1000), value varchar(1000), lang varchar(255), primary key (id)) engine=InnoDB;
create table Domain (active bit not null, atons bit, firingSchedule_id integer, id integer not null, latitude float(23), longitude float(23), publish bit, sortOrder integer, templates bit, zoomLevel integer, color varchar(255), domainId varchar(255), messageSortOrder varchar(255), name varchar(255), timeZone varchar(255), primary key (id)) engine=InnoDB;
create table Domain_Area (Domain_id integer not null, areas_id integer not null) engine=InnoDB;
create table Domain_Category (Domain_id integer not null, categories_id integer not null) engine=InnoDB;
create table Domain_MessageSeries (Domain_id integer not null, messageSeries_id integer not null) engine=InnoDB;
create table Feature (featureCollection_id integer, id integer not null, indexNo integer not null, properties TEXT, uid varchar(255), geometry GEOMETRY not null, primary key (id)) engine=InnoDB;
create table FeatureCollection (id integer not null, uid varchar(255), primary key (id)) engine=InnoDB;
create table FiringPeriod (area_id integer, id integer not null, version integer, created datetime(6), fromDate datetime(6), toDate datetime(6), updated datetime(6), legacyId varchar(255), primary key (id)) engine=InnoDB;
create table FiringSchedule (active bit not null, domain_id integer, id integer not null, scheduleDays integer, targetDomain_id integer, targetMessageSeries_id integer, version integer, created datetime(6), updated datetime(6), primary key (id)) engine=InnoDB;
create table FmReport (id integer not null, sortOrder integer, name varchar(255), params TEXT, properties TEXT, reportId varchar(255) not null, templatePath varchar(255), primary key (id)) engine=InnoDB;
create table FmReport_Domain (FmReport_id integer not null, domains_id integer not null) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table MailingList (active bit not null, id integer not null, version integer, created datetime(6), updated datetime(6), mailingListId varchar(255) not null, primary key (id)) engine=InnoDB;
create table MailingList_Contact (MailingList_id integer not null, contacts_id integer not null) engine=InnoDB;
create table MailingList_User (MailingList_id integer not null, users_id integer not null) engine=InnoDB;
create table MailingListDesc (entity_id integer, id integer not null, description varchar(255), lang varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table MailingListTrigger (id integer not null, mailingList_id integer, publicReport bit, version integer, created datetime(6), nextScheduledExecution datetime(6), updated datetime(6), messageFilter varchar(255), messageQuery varchar(255), scheduledExecutionTime varchar(255), scheduledExecutionTimeZone varchar(255), scheduleType enum ('DAILY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'), type enum ('STATUS_CHANGE','SCHEDULED'), primary key (id)) engine=InnoDB;
create table MailingListTrigger_scriptResourcePaths (MailingListTrigger_id integer not null, indexNo integer not null, scriptResourcePaths varchar(255), primary key (MailingListTrigger_id, indexNo)) engine=InnoDB;
create table MailingListTrigger_statusChanges (MailingListTrigger_id integer not null, statusChanges enum ('DRAFT','VERIFIED','PUBLISHED','EXPIRED','CANCELLED','DELETED')) engine=InnoDB;
create table MailingListTriggerDesc (entity_id integer, id integer not null, lang varchar(255), subject varchar(255), primary key (id)) engine=InnoDB;
create table Message (areaSortOrder FLOAT default 0.0, area_id integer, autoTitle bit not null, createdBy_id integer, hasGeometry bit not null, id integer not null, lastUpdatedBy_id integer, messageSeries_id integer, number integer, originalInformation bit, revision integer not null, separatePage bit, version integer, year integer, created datetime(6), eventDateFrom datetime(6), eventDateTo datetime(6), followUpDate datetime(6), publishDateFrom datetime(6), publishDateTo datetime(6), updated datetime(6), uid varchar(36) not null, repoPath varchar(128) not null, horizontalDatum varchar(255), legacyId varchar(255), shortId varchar(255), thumbnailPath varchar(255), mainType enum ('NW','NM'), status enum ('DRAFT','VERIFIED','PUBLISHED','EXPIRED','CANCELLED','DELETED'), type enum ('PERMANENT_NOTICE','TEMPORARY_NOTICE','PRELIMINARY_NOTICE','MISCELLANEOUS_NOTICE','COASTAL_WARNING','SUBAREA_WARNING','NAVAREA_WARNING','LOCAL_WARNING'), primary key (id)) engine=InnoDB;
create table Message_Area (Message_id integer not null, areas_ORDER integer not null, areas_id integer not null, primary key (Message_id, areas_ORDER)) engine=InnoDB;
create table Message_Category (Message_id integer not null, categories_id integer not null) engine=InnoDB;
create table Message_Chart (Message_id integer not null, charts_ORDER integer not null, charts_id integer not null, primary key (Message_id, charts_ORDER)) engine=InnoDB;
create table MessageDesc (entity_id integer, id integer not null, source varchar(1024), title varchar(1024), internalPublication varchar(2048), publication varchar(2048), lang varchar(255), vicinity varchar(255), primary key (id)) engine=InnoDB;
create table MessageFilter (id integer not null, user_id integer, name varchar(255), parameters varchar(255), primary key (id)) engine=InnoDB;
create table MessageHistory (id integer not null, message_id integer, user_id integer, version integer not null, created datetime(6), snapshot BLOB, status enum ('DRAFT','VERIFIED','PUBLISHED','EXPIRED','CANCELLED','DELETED'), primary key (id)) engine=InnoDB;
create table MessagePart (geometry_id integer, hideSubject bit, id integer not null, indexNo integer not null, message_id integer, type enum ('DETAILS','TIME','POSITIONS','NOTE','PROHIBITION','SIGNALS'), primary key (id)) engine=InnoDB;
create table MessagePartDesc (entity_id integer, id integer not null, subject varchar(500), lang varchar(255), details longtext, primary key (id)) engine=InnoDB;
create table MessageSeries (excludeFromMessageIndex bit, id integer not null, numberSequenceType tinyint, version integer, created datetime(6), updated datetime(6), navtexFormat varchar(255), seriesId varchar(255) not null, shortFormat varchar(255), mainType enum ('NW','NM'), primary key (id)) engine=InnoDB;
create table MessageSeries_editorFields (MessageSeries_id integer not null, editorFields varchar(255)) engine=InnoDB;
create table MessageSeries_types (MessageSeries_id integer not null, types enum ('PERMANENT_NOTICE','TEMPORARY_NOTICE','PRELIMINARY_NOTICE','MISCELLANEOUS_NOTICE','COASTAL_WARNING','SUBAREA_WARNING','NAVAREA_WARNING','LOCAL_WARNING')) engine=InnoDB;
create table MessageSeriesMapping (id integer not null, niordIntegration_id integer, sourceSeriesId varchar(255), targetSeriesId varchar(255), primary key (id)) engine=InnoDB;
create table MessageTag (domain_id integer, id integer not null, locked bit not null, messageCount INT default 0, user_id integer, version integer, created datetime(6), expiryDate datetime(6), updated datetime(6), name varchar(255), tagId varchar(255) not null, type enum ('PRIVATE','DOMAIN','PUBLIC','TEMP'), primary key (id)) engine=InnoDB;
create table MessageTag_Message (messages_id integer not null, tags_id integer not null) engine=InnoDB;
create table NavtexMessagePromulgation (id integer not null, preamble varchar(255), priority enum ('NONE','ROUTINE','IMPORTANT','VITAL'), text longtext, primary key (id)) engine=InnoDB;
create table NavtexMessagePromulgation_NavtexTransmitter (NavtexMessagePromulgation_id integer not null, transmitters_id integer not null) engine=InnoDB;
create table NavtexTransmitter (active bit not null, id integer not null, promulgationType_id integer, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table NavtexTransmitter_Area (NavtexTransmitter_id integer not null, areas_ORDER integer not null, areas_id integer not null, primary key (NavtexTransmitter_id, areas_ORDER)) engine=InnoDB;
create table NiordIntegration (active bit not null, assignNewUids bit not null, createBaseData bit not null, id integer not null, nextScheduledExecution datetime(6), url varchar(255), primary key (id)) engine=InnoDB;
create table ParamType (id integer not null, DTYPE varchar(31) not null, name varchar(255), primary key (id)) engine=InnoDB;
create table ParamType_DictionaryEntry (ListParamType_id integer not null, indexNo integer not null, values_id integer not null, primary key (ListParamType_id, indexNo)) engine=InnoDB;
create table ParamType_TemplateParam (CompositeParamType_id integer not null, indexNo integer not null, templateParams_id integer not null, primary key (CompositeParamType_id, indexNo)) engine=InnoDB;
create table PromulgationType (active bit not null, id integer not null, priority integer not null, version integer, created datetime(6), updated datetime(6), language varchar(255), name varchar(255), serviceId varchar(255), typeId varchar(255) not null, requirement enum ('OPTIONAL','DEFAULT','MANDATORY'), primary key (id)) engine=InnoDB;
create table PromulgationType_Domain (PromulgationType_id integer not null, domains_id integer not null) engine=InnoDB;
create table PromulgationType_messageTypes (PromulgationType_id integer not null, messageTypes enum ('PERMANENT_NOTICE','TEMPORARY_NOTICE','PRELIMINARY_NOTICE','MISCELLANEOUS_NOTICE','COASTAL_WARNING','SUBAREA_WARNING','NAVAREA_WARNING','LOCAL_WARNING')) engine=InnoDB;
create table PromulgationType_scriptResourcePaths (PromulgationType_id integer not null, indexNo integer not null, scriptResourcePaths varchar(255), primary key (PromulgationType_id, indexNo)) engine=InnoDB;
create table Publication (category_id integer, domain_id integer, edition integer, id integer not null, languageSpecific bit not null, messageTag_id integer, revision integer not null, template_id integer, version integer, created datetime(6), publishDateFrom datetime(6), publishDateTo datetime(6), updated datetime(6), publicationId varchar(36) not null, messageTagFilter varchar(255), messageTagFormat varchar(255), printSettings TEXT, repoPath varchar(255), reportParams TEXT, mainType enum ('PUBLICATION','TEMPLATE'), messagePublication enum ('NONE','INTERNAL','EXTERNAL'), periodicalType enum ('DAILY','WEEKLY','MONTHLY','YEARLY'), status enum ('DRAFT','RECORDING','ACTIVE','INACTIVE'), type enum ('NONE','LINK','REPOSITORY','MESSAGE_REPORT'), primary key (id)) engine=InnoDB;
create table PublicationCategory (id integer not null, priority integer not null, publish bit not null, categoryId varchar(255), primary key (id)) engine=InnoDB;
create table PublicationCategoryDesc (entity_id integer, id integer not null, description varchar(255), lang varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table PublicationDesc (entity_id integer, id integer not null, fileName varchar(255), lang varchar(255), link varchar(255), messagePublicationFormat varchar(255), title varchar(255), titleFormat varchar(255), primary key (id)) engine=InnoDB;
create table Reference (id integer not null, indexNo integer not null, message_id integer, type tinyint, messageId varchar(255), primary key (id)) engine=InnoDB;
create table ReferenceDesc (entity_id integer, id integer not null, description varchar(512), lang varchar(255), primary key (id)) engine=InnoDB;
create table SafetyNetArea (active bit not null, id integer not null, promulgationType_id integer, repetition tinyint, sortOrder integer not null, DTYPE varchar(31) not null, center varchar(255), eastings varchar(255), messageAreaPrefix varchar(255), name varchar(255) not null, northings varchar(255), radius varchar(255), swCorner varchar(255), coastalArea enum ('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'), navarea enum ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI'), primary key (id)) engine=InnoDB;
create table SafetyNetMessagePromulgation (area_id integer, id integer not null, safetyNetId varchar(255), priority enum ('SAFETY','URGENCY','DISTRESS'), text longtext, primary key (id)) engine=InnoDB;
create table ScheduledMail (attempts integer not null, id integer not null, created datetime(6), sendDate datetime(6), lastError varchar(255), sender varchar(255), subject varchar(255), contents LONGBLOB, status enum ('PENDING','SENT','ERROR'), primary key (id)) engine=InnoDB;
create table ScheduledMailRecipient (id integer not null, mail_id integer, address varchar(255), recipientType enum ('TO','CC','BCC'), primary key (id)) engine=InnoDB;
create table ScriptResource (id integer not null, version integer, created datetime(6), updated datetime(6), path varchar(255), content longtext, type enum ('FM','JS'), primary key (id)) engine=InnoDB;
create table ScriptResourceHistory (id integer not null, resource_id integer, user_id integer, version integer not null, created datetime(6), snapshot BLOB, primary key (id)) engine=InnoDB;
create table Sequence (nextValue bigint not null, name varchar(255) not null, primary key (name)) engine=InnoDB;
create table Setting (cached bit not null, editable bit not null, web bit not null, setting_value varchar(2000), description varchar(255), setting_key varchar(255) not null, type enum ('String','Password','Integer','Long','Float','Double','Date','Boolean','Path','json'), primary key (setting_key)) engine=InnoDB;
create table Source (active bit not null, id integer not null, primary key (id)) engine=InnoDB;
create table SourceDesc (entity_id integer, id integer not null, abbreviation varchar(255), lang varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table TemplateParam (id integer not null, indexNo integer not null, mandatory bit not null, positionList bit not null, paramId varchar(255), type varchar(255), primary key (id)) engine=InnoDB;
create table TemplateParamDesc (entity_id integer, id integer not null, lang varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table TwitterMessagePromulgation (id integer not null, tweet varchar(512), primary key (id)) engine=InnoDB;
create table TwitterSettings (id integer not null, includeThumbnail bit, promulgationType_id integer, accessToken varchar(255), accessTokenSecret varchar(255), apiKey varchar(255), apiSecret varchar(255), format varchar(255), primary key (id)) engine=InnoDB;
create table User (id integer not null, version integer, created datetime(6), updated datetime(6), email varchar(255), firstName varchar(255), language varchar(255), lastName varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table AreaDesc add constraint UK3awmx2g9mp30n9o2bdd3p9ogf unique (lang, entity_id);
create index aton_tag_k on AtonTag (k);
create index aton_tag_v on AtonTag (v);
alter table AttachmentDesc add constraint UKbt3um3dw9kqxf3wenhc7vyuwa unique (lang, entity_id);
create index batch_data_instance_id on BatchData (instanceId);
alter table Category_TemplateParam add constraint UK_8evxi9991q2xrhttqhfml5puo unique (templateParams_id);
alter table CategoryDesc add constraint UKr3bldinkjkw93lw8xtrx3vskt unique (lang, entity_id);
alter table Chart add constraint chart_chart_number unique (chartNumber);
alter table Contact add constraint contact_email unique (email);
alter table Dictionary add constraint UK_fvg089g4hibx9evybwsrro05u unique (name);
alter table DictionaryEntryDesc add constraint UKraui9u28dyvj6cn7kfrkoafx5 unique (lang, entity_id);
alter table Domain add constraint domain_domain_id unique (domainId);
alter table Domain add constraint UK_9bw3up4aitusgqxt85gajur7c unique (firingSchedule_id);
alter table Feature add constraint feature_uid unique (uid);
alter table FeatureCollection add constraint feature_collection_uid unique (uid);
create index firing_period_from_date on FiringPeriod (fromDate);
create index firing_period_to_date on FiringPeriod (toDate);
alter table FiringSchedule add constraint UK_f8s8vh15mtinyfaoycuo448gt unique (domain_id);
alter table FmReport add constraint UK_tnhwptt0rvkkf3w9ror1rwb3i unique (reportId);
alter table MailingList add constraint UK_lmoik92xwc1fh8cbxdd35vbnx unique (mailingListId);
alter table MailingListDesc add constraint UK4sechbk8ft9yt2t9fmqrhpitc unique (lang, entity_id);
alter table MailingListTriggerDesc add constraint UKfvnywmgduv1wed3xcxlpbf2y0 unique (lang, entity_id);
create index message_uid_k on Message (uid);
create index message_type_k on Message (type);
create index message_main_type_k on Message (mainType);
create index message_status_k on Message (status);
create index message_legacy_id_k on Message (legacyId);
alter table Message add constraint UK_3m213vallnceq0nm9opb5fifl unique (uid);
alter table Message add constraint UK_4i8w8pf7oqxahfgoq4kee907n unique (repoPath);
alter table MessageDesc add constraint UK9nvcc6n21wrwtfv9vif10ak86 unique (lang, entity_id);
alter table MessageFilter add constraint UK9bdyxhnsahtpiisysmfo9mn00 unique (name, user_id);
alter table MessagePart add constraint UK_hlyy0sji8fx0518wjkxet0t5p unique (geometry_id);
alter table MessagePartDesc add constraint UKade4hi21pkvm4dtjxhf0wve0k unique (lang, entity_id);
alter table MessageSeries add constraint UK_3373wuwyw2yafgj18v88tdn5a unique (seriesId);
create index message_tag_type_k on MessageTag (type);
create index message_tag_id_k on MessageTag (tagId);
alter table MessageTag add constraint UK_s67gpda22794db7co786lqxxx unique (tagId);
alter table NavtexTransmitter add constraint UK_tfje74aa7ijg2y1p1efsfoafd unique (name);
alter table ParamType add constraint UK_lb94wnkd8r5pw041n1atdyo3g unique (name);
alter table ParamType_TemplateParam add constraint UK_flhv81lkefowtpwdssfi5mli8 unique (templateParams_id);
alter table PromulgationType add constraint UK_6p18vatyqedx1sm2fu2iicocy unique (typeId);
create index publication_id_k on Publication (publicationId);
create index publication_type_k on Publication (type);
create index publication_main_type_k on Publication (mainType);
create index publication_status_k on Publication (status);
alter table Publication add constraint UK_qccfg05ap9rxtsvm75s1pjfuh unique (publicationId);
alter table PublicationCategory add constraint UK_1de79dilas812edmhd9rfor99 unique (categoryId);
alter table PublicationCategoryDesc add constraint UKanmhvnap9pyakyg3pkdalnat3 unique (lang, entity_id);
alter table PublicationDesc add constraint UK38ux0yyqyc44jhwsajfnih8gr unique (lang, entity_id);
create index reference_message_id_k on Reference (messageId);
alter table ReferenceDesc add constraint UKsmudg5dbnnkg1idh4fvs2oiaf unique (lang, entity_id);
alter table SafetyNetArea add constraint UK_owxoyjc7scmiciesnc52m06x5 unique (name);
create index scheduled_mail_send_date on ScheduledMail (sendDate);
create index scheduled_mail_status on ScheduledMail (status);
alter table ScriptResource add constraint UK_h7yqoek130rw15ny1iqa88pw2 unique (path);
alter table SourceDesc add constraint UKsryv1woa0xshor3iut0ymrk14 unique (lang, entity_id);
alter table TemplateParamDesc add constraint UKi1a4gbis3bwvwnqg6bmcu6m2f unique (lang, entity_id);
alter table User add constraint user_username unique (username);
alter table Area add constraint FKok0rb6fmp3gsrdx0t4o1nycid foreign key (parent_id) references Area (id);
alter table Area_editorFields add constraint FK6vsnl843mbjjdkd6nghfgwb3m foreign key (Area_id) references Area (id);
alter table AreaDesc add constraint FKiqnqan0ief1w4y84xr90xf6n2 foreign key (entity_id) references Area (id);
alter table AtonTag add constraint FKhe4s80pw2s53462fw7fw68esu foreign key (atonNode_id) references AtonNode (id);
alter table Attachment add constraint FKpwve9lcb788oohmqp9ws9qnkb foreign key (message_id) references Message (id);
alter table AttachmentDesc add constraint FKk7brhbpxca0h5iggpyrigds22 foreign key (entity_id) references Attachment (id);
alter table BaseMessagePromulgation add constraint FKjg31pdvdc70s0jm6b13l2emrw foreign key (message_id) references Message (id);
alter table BaseMessagePromulgation add constraint FK80ggstojxd385106cj58vscoi foreign key (type_id) references PromulgationType (id);
alter table BatchData add constraint FKmjj65f5o8i2mv8kmukh7oaw28 foreign key (domain_id) references Domain (id);
alter table BatchData add constraint FKd6wy5nbd6sidy5i3tks0kk1fq foreign key (user_id) references User (id);
alter table Category add constraint FK5s5t2pfpxo0vnd1ihc43721ty foreign key (parent_id) references Category (id);
alter table Category_Domain add constraint FKdqygl3e6uiypvekjs5ajefox2 foreign key (domains_id) references Domain (id);
alter table Category_Domain add constraint FKb2ethwsekl1ntaib6te43ln3l foreign key (Category_id) references Category (id);
alter table Category_editorFields add constraint FKkwo8wi0d8s9fvf7qooxwph2ss foreign key (Category_id) references Category (id);
alter table Category_scriptResourcePaths add constraint FKfv5gn5mvwkdhvoc31qdd6ko5u foreign key (Category_id) references Category (id);
alter table Category_stdTemplateFields add constraint FKfsxsdsmegwa26spbur7i4md5x foreign key (Category_id) references Category (id);
alter table Category_TemplateParam add constraint FKn6lx1rhe667h498res7n3l1f4 foreign key (templateParams_id) references TemplateParam (id);
alter table Category_TemplateParam add constraint FKh2d4ya6j452xr8b9a20qe1crp foreign key (Category_id) references Category (id);
alter table CategoryDesc add constraint FK5scvvfivtm5ud09oxe4cvsxjd foreign key (entity_id) references Category (id);
alter table Comment add constraint FKm9t08bew9t9e956fviaux9fec foreign key (acknowledgedBy_id) references User (id);
alter table Comment add constraint FKr6obs0bvtyg53rqlwu3hmg7mw foreign key (message_id) references Message (id);
alter table Comment add constraint FKhlbnnmiua9xpvfq8y1u1a15ie foreign key (user_id) references User (id);
alter table Comment_emailAddresses add constraint FKih4tkku8hsexb33yhhtqe434v foreign key (Comment_id) references Comment (id);
alter table DateInterval add constraint FKp8j4h5prexj5877ltouwrt7y4 foreign key (messagePart_id) references MessagePart (id);
alter table DictionaryEntry add constraint FKigbd9uvyayagydsjn7iswb575 foreign key (dictionary_id) references Dictionary (id);
alter table DictionaryEntryDesc add constraint FKd01vibf7aowx4kg00oeed91j3 foreign key (entity_id) references DictionaryEntry (id);
alter table Domain add constraint FKo69rpccguuwv3wqvfcamuw9vs foreign key (firingSchedule_id) references FiringSchedule (id);
alter table Domain_Area add constraint FKfmwj4run1womiqrfmwps8lhry foreign key (areas_id) references Area (id);
alter table Domain_Area add constraint FK5chnoidt4jm72l6jpdp0a85kj foreign key (Domain_id) references Domain (id);
alter table Domain_Category add constraint FKepr6r5y9pq3iajjl6ilcpbrl6 foreign key (categories_id) references Category (id);
alter table Domain_Category add constraint FK520n20ginqrrmo3wfeoey1inp foreign key (Domain_id) references Domain (id);
alter table Domain_MessageSeries add constraint FKnjas15121k4nmfx15bx9sords foreign key (messageSeries_id) references MessageSeries (id);
alter table Domain_MessageSeries add constraint FKdkesbsjr940gbsssa5dreqvbk foreign key (Domain_id) references Domain (id);
alter table Feature add constraint FK7rgrlw3l37htj8y9x4jqqcpt8 foreign key (featureCollection_id) references FeatureCollection (id);
alter table FiringPeriod add constraint FKokjpsiah3h6u8opv7dpkje4h4 foreign key (area_id) references Area (id);
alter table FiringSchedule add constraint FK9td1dvq8a826xqkc7x4tp8mlr foreign key (domain_id) references Domain (id);
alter table FiringSchedule add constraint FKo66idni7eedr6po549vhs050v foreign key (targetDomain_id) references Domain (id);
alter table FiringSchedule add constraint FKjedd060xb6vk9rfrvbxsealp6 foreign key (targetMessageSeries_id) references MessageSeries (id);
alter table FmReport_Domain add constraint FKr5h433ayuacpj52se01hidu9c foreign key (domains_id) references Domain (id);
alter table FmReport_Domain add constraint FKnsj3prt31tu1s86rtww847fd6 foreign key (FmReport_id) references FmReport (id);
alter table MailingList_Contact add constraint FKekb05y14jb96uugts80g4u3lg foreign key (contacts_id) references Contact (id);
alter table MailingList_Contact add constraint FKdx0d9c9mifhi32qhrm3uemvnd foreign key (MailingList_id) references MailingList (id);
alter table MailingList_User add constraint FK41jmirdr2f8vinpw2siyoc25b foreign key (users_id) references User (id);
alter table MailingList_User add constraint FKk0fktseyiyxiyxmhbrsdiaejk foreign key (MailingList_id) references MailingList (id);
alter table MailingListDesc add constraint FK57cg00cofir9dv9fyr3ycugk8 foreign key (entity_id) references MailingList (id);
alter table MailingListTrigger add constraint FK6yl1ss6cbuwd3po1l611wrpp1 foreign key (mailingList_id) references MailingList (id);
alter table MailingListTrigger_scriptResourcePaths add constraint FK11cn8u4hj0l3wgneml3v4gpca foreign key (MailingListTrigger_id) references MailingListTrigger (id);
alter table MailingListTrigger_statusChanges add constraint FK88ghwpoofegbwjegkbdf7yy6x foreign key (MailingListTrigger_id) references MailingListTrigger (id);
alter table MailingListTriggerDesc add constraint FK535ewtwjjuhf060ad0ipbin23 foreign key (entity_id) references MailingListTrigger (id);
alter table Message add constraint FKsuwen6mo41xphxw0wkolmgktg foreign key (area_id) references Area (id);
alter table Message add constraint FK24lkys2jh4igc06w3arhv1elr foreign key (createdBy_id) references User (id);
alter table Message add constraint FKgnoqxjkvrj0p0ctax1iifgoei foreign key (lastUpdatedBy_id) references User (id);
alter table Message add constraint FK45v0ekmhhl0r9wrnabv37teqk foreign key (messageSeries_id) references MessageSeries (id);
alter table Message_Area add constraint FKd1m6l6qteil3bfb8nrwrf3t1k foreign key (areas_id) references Area (id);
alter table Message_Area add constraint FK7hkr4n1b3o9dqkudrlwq2hlku foreign key (Message_id) references Message (id);
alter table Message_Category add constraint FK3mlpqrdwb68lkdi1tkf8sah3a foreign key (categories_id) references Category (id);
alter table Message_Category add constraint FKcx9t6u1roct367teax4ppt8jm foreign key (Message_id) references Message (id);
alter table Message_Chart add constraint FKiqkspslbh6mvfrkqa66l8ssj6 foreign key (charts_id) references Chart (id);
alter table Message_Chart add constraint FKo7589wtfk0y4vg1x49a50osmm foreign key (Message_id) references Message (id);
alter table MessageDesc add constraint FK4ojdfia7glr08yu8tp6aclab4 foreign key (entity_id) references Message (id);
alter table MessageFilter add constraint FKkbve7xrns8po3lp8kglitv800 foreign key (user_id) references User (id);
alter table MessageHistory add constraint FK7ucuwkok5gcaqxprctdn82gv6 foreign key (message_id) references Message (id);
alter table MessageHistory add constraint FKtqlgse9mc99r6x97bh9i0xknj foreign key (user_id) references User (id);
alter table MessagePart add constraint FKgl9dbhfj7gln7evk95rio84oo foreign key (geometry_id) references FeatureCollection (id);
alter table MessagePart add constraint FK5yu80lvxrlxxeq5r3bar7hnv7 foreign key (message_id) references Message (id);
alter table MessagePartDesc add constraint FKm87afxou1jvj1otuk1givhr6a foreign key (entity_id) references MessagePart (id);
alter table MessageSeries_editorFields add constraint FKqo8yqhhl3lneop1o96k4gx9jg foreign key (MessageSeries_id) references MessageSeries (id);
alter table MessageSeries_types add constraint FK8nuyc9mpvf9tvw5rjrqq7r3e2 foreign key (MessageSeries_id) references MessageSeries (id);
alter table MessageSeriesMapping add constraint FKmfiwwwlscsxn5a2unwi3incek foreign key (niordIntegration_id) references NiordIntegration (id);
alter table MessageTag add constraint FK1w3hqnxi8j76y3rsta8ulv8qf foreign key (domain_id) references Domain (id);
alter table MessageTag add constraint FKwckjkeilg810iew66y7qn2qh foreign key (user_id) references User (id);
alter table MessageTag_Message add constraint FKd2u8aj3tn8akunko2ngnf8eh7 foreign key (messages_id) references Message (id);
alter table MessageTag_Message add constraint FKpducl4oc5f09moxirgulikfia foreign key (tags_id) references MessageTag (id);
alter table NavtexMessagePromulgation add constraint FK632xjg450bn3lq4io88bmgdu8 foreign key (id) references BaseMessagePromulgation (id);
alter table NavtexMessagePromulgation_NavtexTransmitter add constraint FKcxj7je012gm7xh4gggjrubfpu foreign key (transmitters_id) references NavtexTransmitter (id);
alter table NavtexMessagePromulgation_NavtexTransmitter add constraint FKi73vs4090c0ua65nx53sf7q24 foreign key (NavtexMessagePromulgation_id) references NavtexMessagePromulgation (id);
alter table NavtexTransmitter add constraint FKresfone4gc6ls3p3cwft2uxrf foreign key (promulgationType_id) references PromulgationType (id);
alter table NavtexTransmitter_Area add constraint FKmhn4u0vld8s554c39nniwhbtd foreign key (areas_id) references Area (id);
alter table NavtexTransmitter_Area add constraint FK14ltsr52jpqq3kx3249k0lytc foreign key (NavtexTransmitter_id) references NavtexTransmitter (id);
alter table ParamType_DictionaryEntry add constraint FKoq8dhcqf6vlegtbxvlyh0pnfe foreign key (values_id) references DictionaryEntry (id);
alter table ParamType_DictionaryEntry add constraint FKs2uyt2akp2n0ixkfx8v9hy25g foreign key (ListParamType_id) references ParamType (id);
alter table ParamType_TemplateParam add constraint FKetmtsuxvtv8waqjqawcnq0196 foreign key (templateParams_id) references TemplateParam (id);
alter table ParamType_TemplateParam add constraint FKp504927i4pwd1val5t780wf7s foreign key (CompositeParamType_id) references ParamType (id);
alter table PromulgationType_Domain add constraint FKrojsi5b2o3o9mtiu3qdg7mrtb foreign key (domains_id) references Domain (id);
alter table PromulgationType_Domain add constraint FKmson6ywy2o8r9ehb63e1i2nx9 foreign key (PromulgationType_id) references PromulgationType (id);
alter table PromulgationType_messageTypes add constraint FK32lxk3otrq9m8wuwaqtwvwitb foreign key (PromulgationType_id) references PromulgationType (id);
alter table PromulgationType_scriptResourcePaths add constraint FKt4cbs7v8a16vrs8oxy70r7utc foreign key (PromulgationType_id) references PromulgationType (id);
alter table Publication add constraint FK7yv84df129bl2ovjdxw2v964 foreign key (category_id) references PublicationCategory (id);
alter table Publication add constraint FKmooua32m18xj39hdxgjahpq6q foreign key (domain_id) references Domain (id);
alter table Publication add constraint FKqkdt8fg3cuvdo0uvp3asmyrnj foreign key (messageTag_id) references MessageTag (id);
alter table Publication add constraint FKkompkq8i5m7ibg9h38vfdg05g foreign key (template_id) references Publication (id);
alter table PublicationCategoryDesc add constraint FK6pwh9eodtrnk5wfucmln7yp74 foreign key (entity_id) references PublicationCategory (id);
alter table PublicationDesc add constraint FK8uoa78i6jwy67rlqlww6xa6t2 foreign key (entity_id) references Publication (id);
alter table Reference add constraint FK9axat5mh3uu0ddmvy2mw8lp08 foreign key (message_id) references Message (id);
alter table ReferenceDesc add constraint FKa2urktbrpk4u1r7lc7f3opxs foreign key (entity_id) references Reference (id);
alter table SafetyNetArea add constraint FKi4ukvdvl507vbi8iq8dsakd9 foreign key (promulgationType_id) references PromulgationType (id);
alter table SafetyNetMessagePromulgation add constraint FK994mfrf0nmm0odrak65p3u9fr foreign key (area_id) references SafetyNetArea (id);
alter table SafetyNetMessagePromulgation add constraint FKaeeqsbqbhjgdg0rio4ga6gigi foreign key (id) references BaseMessagePromulgation (id);
alter table ScheduledMailRecipient add constraint FK9f0nht452b3c7cpw6ymm8yy8k foreign key (mail_id) references ScheduledMail (id);
alter table ScriptResourceHistory add constraint FK7rt2g48qhe6j5a1uet3m10shm foreign key (resource_id) references ScriptResource (id);
alter table ScriptResourceHistory add constraint FKpg6y8ab9ykpjwt0xcpwouinht foreign key (user_id) references User (id);
alter table SourceDesc add constraint FKl35p59mn6mtaxhcb7itfwapqq foreign key (entity_id) references Source (id);
alter table TemplateParamDesc add constraint FKcvidqw2yn97e3algk7hchym2j foreign key (entity_id) references TemplateParam (id);
alter table TwitterMessagePromulgation add constraint FKar01b3vushxhslx9na85pyj5v foreign key (id) references BaseMessagePromulgation (id);
alter table TwitterSettings add constraint FKcpb5y3rjfqxf9p1k0w448gr9r foreign key (promulgationType_id) references PromulgationType (id);
