# trigger:
# - master

stages:
  - stage: Build_niord
    displayName: Build niord application(niord -> niord-dk)
    jobs:
    - job: Building_niord_job
      displayName: Build niord
      pool:
        vmImage: ubuntu-latest

      steps:
        - task: Bash@3
          displayName: Download Maven
          inputs:
            targetType: 'inline'
            script: 'wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip'

        - task: ExtractFiles@1
          displayName: 'Unzip Maven'
          inputs:
              archiveFilePatterns: 'apache-maven-3.6.3-bin.zip'
              destinationFolder: '$(build.sourcesdirectory)/maven'
        # - task: Maven@3
        #   displayName: 'Build niord'
        #   retryCountOnTaskFailure: 3
        #   inputs:
        #     mavenPomFile: 'pom.xml'
        #     mavenOptions: '-Xmx3072m'
        #     javaHomeOption: 'JDKVersion'
        #     jdkVersionOption: '1.11'
        #     jdkArchitectureOption: 'x64'
        #     mavenVersionOption: 'Path'
        #     mavenDirectory: '$(build.sourcesdirectory)/maven/apache-maven-3.6.3'
        #     mavenSetM2Home: true
        #     publishJUnitResults: true
        #     testResultsFiles: '**/surefire-reports/TEST-*.xml'
        #     goals: 'clean install'

        - task: Bash@3
          displayName: Clone niord-dk repo
          inputs:
            targetType: 'inline'
            script: 'git clone https://github.com/NiordOrg/niord-dk.git'
        
        # - task: Maven@3
        #   displayName: 'Build niord-dk'
        #   retryCountOnTaskFailure: 3
        #   inputs:
        #     mavenPomFile: './niord-dk/pom.xml'
        #     mavenOptions: '-Xmx3072m'
        #     javaHomeOption: 'JDKVersion'
        #     jdkVersionOption: '1.11'
        #     jdkArchitectureOption: 'x64'
        #     mavenVersionOption: 'Path'
        #     mavenDirectory: '$(build.sourcesdirectory)/maven/apache-maven-3.6.3'
        #     mavenSetM2Home: true
        #     publishJUnitResults: true
        #     testResultsFiles: '**/surefire-reports/TEST-*.xml'
        #     goals: '-P dist clean install'
            
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'ls -R'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              mkdir -p niord-dk/niord-dk-web/target
              touch niord-dk/niord-dk-web/target/niord-dk-web.war
              ls -R niord-dk/niord-dk-web/target
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: ./niord-dk/niord-dk-web/target
            artifactName: app


  - stage: Build_Wildfly
    dependsOn: Build_Niord
    displayName: Build Wildfly
    jobs:
    - job: Build_wildfly
      displayName: Build wildfly
      pool:
        vmImage: ubuntu-latest

      steps:
      - task: Bash@3
        displayName: Clone niord-wildfly repo
        inputs:
          targetType: 'inline'
          script: 'git clone https://github.com/NiordOrg/niord-wildfly.git'

      - task: Bash@3
        displayName: Build wildfly
        inputs:
          targetType: 'inline'
          script: './niord-wildfly/build/build-wildfly.sh'

      - task: Bash@3
        displayName: DEBUG
        inputs:
          targetType: 'inline'
          script: |
            ls -R
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: niordDKBuild

      - task: Bash@3
        displayName: DEBUG
        inputs:
          targetType: 'inline'
          script: |
            ls -R

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.ArtifactStagingDirectory)'
          Contents: 'niord-dk-web.war'
          TargetFolder: './niord-wildfly/wildfly-$(wildflu_version).Final/standalone/deployments'