/*
 * Copyright 2026 Danish Emergency Management Agency.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.niord.core.publication.series;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Every declared invariant is bound to a named assertion.
 *
 * The id list is GENERATED from the specification, so a rule added there and
 * never bound here is a red build. The bindings are declared, because only a
 * person can say which test covers which rule -- but the list they are checked
 * against is not, which is what stops the two drifting.
 *
 * The rules were prose before this existed, and prose is exactly the class the
 * publicTo capping bugs fell into: a retro-created gap issue never getting its
 * own publicTo, and imported issues left MANUAL so two current editions reach
 * the public site. Both read perfectly well. Both were wrong.
 */
public class InvariantManifestTest {

    /** Where the bindings live. Scanned as source, so no classpath scanner is needed. */
    private static final Path TEST_SOURCES = Paths.get("src", "test", "java");

    /**
     * Tasks that may own a @Pending. Anything else is a typo or a task that does
     * not exist.
     *
     * DATA, not a citation. These ids are the closed vocabulary a @Pending
     * annotation is checked against, so they are values this test compares
     * against rather than a reference to anything outside the repository -- which
     * is why they survive here where the same ids in a comment do not.
     */
    private static final Set<String> KNOWN_TASKS = new LinkedHashSet<>(List.of(
            "B1.7b", "B2.1", "B2.2", "B2.3a", "B2.3b", "B2.4", "B2.5", "B2.6", "B2.7", "B2.8",
            "B2.9", "B2.10", "B2.11", "B2.12",
            "B3.1", "B3.2", "B3.3a", "B3.3b", "B3.3c", "B3.4a", "B3.4b", "B3.4c", "B3.5", "B3.6", "B3.7",
            "B4.1", "B4.2", "B4.3", "B4.4", "B4.5", "B4.6", "B4.7",
            "B5.1", "B5.2", "B5.3", "B5.4a", "B5.4b", "B5.4c", "B5.5", "B5.6", "B5.7",
            "B6.1", "B6.2", "B6.3", "B7.1", "B7.2", "B7.3", "B7.4"));

    private static final Pattern BINDS = Pattern.compile(
            "@BindsRule\\s*\\(\\s*(?:value\\s*=\\s*)?\\{?([^}\\)]*)\\}?\\s*(?:,\\s*pending\\s*=\\s*\"([^\"]*)\")?\\s*\\)");
    private static final Pattern ID = Pattern.compile("\"([A-Z]{1,2}-\\d{1,2})\"");

    /** id -> the owning task if pending, or null if asserted for real. */
    private record Binding(String id, String pendingOwner, String file) {
    }

    // ------------------------------------------------------------------ the list

    private static List<String> declaredRuleIds() throws IOException {
        try (InputStream in = InvariantManifestTest.class.getResourceAsStream("/rule-ids.txt")) {
            assertNotNull(in, "rule-ids.txt is missing; it is generated by gen-rule-ids.js in niord-app");
            List<String> ids = new ArrayList<>();
            for (String line : new String(in.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
                String trimmed = line.trim();
                if (!trimmed.isEmpty() && !trimmed.startsWith("#")) {
                    ids.add(trimmed);
                }
            }
            return ids;
        }
    }

    // -------------------------------------------------------------- the bindings

    private static Map<String, Binding> scanBindings() throws IOException {
        Map<String, Binding> bound = new LinkedHashMap<>();
        if (!Files.isDirectory(TEST_SOURCES)) {
            fail("cannot find " + TEST_SOURCES.toAbsolutePath() + "; the manifest scan needs the test sources");
        }
        try (Stream<Path> files = Files.walk(TEST_SOURCES)) {
            for (Path file : files.filter(f -> f.toString().endsWith(".java")).toList()) {
                String source = Files.readString(file, StandardCharsets.UTF_8);
                Matcher m = BINDS.matcher(source);
                while (m.find()) {
                    String pending = m.group(2);
                    Matcher ids = ID.matcher(m.group(1));
                    while (ids.find()) {
                        bound.put(ids.group(1), new Binding(ids.group(1),
                                pending == null || pending.isBlank() ? null : pending,
                                file.getFileName().toString()));
                    }
                }
            }
        }
        return bound;
    }

    // ------------------------------------------------------------------- the test

    @Test
    public void everyDeclaredInvariantIsBoundToAnAssertion() throws IOException {
        List<String> declared = declaredRuleIds();
        assertTrue(declared.size() >= 90,
                "only " + declared.size() + " rule ids were read; the generated list looks truncated");

        Map<String, Binding> bound = scanBindings();

        List<String> unbound = declared.stream().filter(id -> !bound.containsKey(id)).toList();
        List<String> pendingWithoutOwner = bound.values().stream()
                .filter(b -> "".equals(b.pendingOwner()))
                .map(Binding::id).toList();
        List<String> pendingWithUnknownOwner = bound.values().stream()
                .filter(b -> b.pendingOwner() != null && !KNOWN_TASKS.contains(b.pendingOwner()))
                .map(b -> b.id() + " -> " + b.pendingOwner()).toList();
        List<String> boundButUndeclared = bound.keySet().stream()
                .filter(id -> !declared.contains(id)).toList();

        long pending = bound.values().stream().filter(b -> b.pendingOwner() != null).count();
        long asserted = bound.size() - pending;

        System.out.println();
        System.out.println("  invariant manifest: " + declared.size() + " declared, "
                + asserted + " asserted, " + pending + " pending, " + unbound.size() + " unbound");
        System.out.println();

        List<String> problems = new ArrayList<>();
        if (!unbound.isEmpty()) {
            problems.add("no binding at all for " + unbound.size() + " rule(s): " + unbound);
        }
        if (!pendingWithoutOwner.isEmpty()) {
            problems.add("@Pending with no owning task: " + pendingWithoutOwner);
        }
        if (!pendingWithUnknownOwner.isEmpty()) {
            problems.add("@Pending naming a task that does not exist: " + pendingWithUnknownOwner);
        }
        if (!boundButUndeclared.isEmpty()) {
            problems.add("bound to an id the specification does not declare: " + boundButUndeclared);
        }

        if (!problems.isEmpty()) {
            fail("the invariant manifest does not hold:\n  " + String.join("\n  ", problems));
        }
    }

    /**
     * The pending count is printed, not hidden.
     *
     * The invariant-binding pass is what drives it to zero, and it cannot run until the
     * transactional actions exist. Until then the number is the honest measure of
     * how much of the rule set is still prose.
     */
    @Test
    public void thePendingCountIsVisible() throws IOException {
        Map<String, Binding> bound = scanBindings();
        long pending = bound.values().stream().filter(b -> b.pendingOwner() != null).count();

        Map<String, Long> byOwner = new LinkedHashMap<>();
        for (Binding b : bound.values()) {
            if (b.pendingOwner() != null) {
                byOwner.merge(b.pendingOwner(), 1L, Long::sum);
            }
        }

        System.out.println("  pending invariants by owning task:");
        byOwner.entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .forEach(e -> System.out.println("    " + e.getKey() + "  " + e.getValue()));
        System.out.println("  total pending: " + pending);
        System.out.println();

        assertTrue(pending >= 0);
    }
}
