name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    timeout-minutes: 30
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 15 ]
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
           
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn --batch-mode --update-snapshots verify
